### ISSUE TITLE
Docker Build Fails due to change of debian sources

### ISSUE THREAD

**Issue by albertnanda** [RTIInternational/SMART#11]
ubuntu:~/dj/SMART/envs/dev$ sudo docker-compose build
postgres uses an image, skipping
redis uses an image, skipping
Building smart_backend
Step 1/8 : FROM python:3.5.3
 ---> 56b15234ac1d
Step 2/8 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> da52f44df65a
Step 3/8 : RUN apt-get update && apt-get install -y netcat-traditional
 ---> Running in 171feffc12f4
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Err http://deb.debian.org jessie-updates/main amd64 Packages

Get:4 http://security.debian.org jessie/updates/main amd64 Packages [823 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
Fetched 10.1 MB in 7s (1343 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'smart_backend' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y netcat-traditional' returned a non-zero code: 100

**Comment by wengerm50** [comment]
Hi, Thanks for brining this to our attention!

I've gone ahead and bumped up the version of the python images (which in turns bumped up the Debian version) our environment uses.  This should fix the issue.

If you run into any other issues, please let us know.
