### ISSUE TITLE
Issues with Batch Size 

### ISSUE THREAD

**Issue by preetham-salehundam** [RTIInternational/SMART#16]
I have uploaded close to 15000 records and i can only a batch size of 150 as specified, How can i see the remaining tweets?

**Comment by rchew** [comment]
If you'd like to see the tweets that you've labeled (or that your team has labeled), you can view the "History" page or the Admin dashboard: 

- https://smart-app.readthedocs.io/en/latest/tutorial-annotate.html#history-page
- https://smart-app.readthedocs.io/en/latest/tutorial-admin-dash.html#labeled-data-page

If you'd like to see other tweets that have yet be labeled, you can view the "Fix Skew" page:

- https://smart-app.readthedocs.io/en/latest/tutorial-annotate.html#fix-skew-page

**Comment by rchew** [comment]
@preetham-salehundam let me know if you're still having problems, and I'll re-open the issue.
