### ISSUE TITLE
Model not running

### ISSUE THREAD

**Issue by aresaguilar-returnly** [RTIInternational/SMART#55]
I've created a project and added some data, but the model is not being retrained even after I label lots of data. These are the project settings:
- Classifier: logistic regression
- Selection Algorithm: least confident
- Batch Size: 20 (I've also tested different batch sizes)
- No IRR being used (I've also tested with different IRR values)
- Number of samples: 1000 labeled and 10000 not labeled
- Number of labels: 23

Is there something I'm doing wrong? When is the model supposed to be retrained?

**Comment by rchew** [comment]
Hi Ares,

With the inputs you've described, the model should be running in the background between batches.  If this is working correctly, you should see the model progress on the Modeling tab of the Admin page:

https://smart-app.readthedocs.io/en/latest/tutorial-admin-dash.html#active-learning-model-page

Given that you have 23 categories, another wrinkle that be influencing the model training is if there are categories that do not yet have any labeled examples.  By default, the app will continue selecting random observations from the unlabeled dataset until there's at least one labeled observation per category.  See below for more details:

https://smart-app.readthedocs.io/en/latest/tutorial-annotate.html#refilling-the-batch

One way to help deal with this within SMART is using the Fix Skew option on the Annotation page:

https://smart-app.readthedocs.io/en/latest/tutorial-annotate.html#fix-skew-page

If neither of these seem to be the issue, lmk we'll try to diagnose.

**Comment by aresaguilar-returnly** [comment]
Hi Rob!

I've double checked your points, but still no luck. I manually labelled at least two samples for each class, using the 'Fix Skew' option, but the model hasn't been trained yet (the Modelling tab only shows one point).

Please let me know what can I do to debug this issue, thanks a lot!

**Comment by aresaguilar-returnly** [comment]
I'm closing this as there was no bug, the model only is trained after samples from all labels have been annotated, however I think this should be in the documentation. Thanks a lot for your help!
